### ISSUE TITLE
ionic creator not working in chromium

### ISSUE THREAD

**Issue by 3x14159265** [driftyco/ionic-creator-issues#127]
I can't drop components to the app in Chromium (Version 37.0.2062.120 Ubuntu 14.04 (281580) (64-bit).
Here is the output of the console:

```javascript
//creator.ionic.io/dist/ionic-creator.js?8:2:13192)
    at J (http://creator.ionic.io/dist/ionic-creator.js?8:3:29578)
    at Q (http://creator.ionic.io/dist/ionic-creator.js?8:3:30463)
    at HTMLDocument.gt (http://creator.ionic.io/dist/ionic-creator.js?8:4:2628)
TypeError: Cannot read property 'match' of null
    at Object.markId (http://creator.ionic.io/dist/ionic-creator.js?8:2:11457)
    at http://creator.ionic.io/dist/ionic-creator.js?8:3:23817
    at Scope.$emit (http://creator.ionic.io/lib/offline/angular.js:12732:33)
    at Object.obj.appendChild (http://creator.ionic.io/dist/ionic-creator.js?8:1:15889)
    at Object.e.add.obj.addDefaultChildren (http://creator.ionic.io/dist/ionic-creator.js?8:1:8988)
    at Object.createComponent (http://creator.ionic.io/dist/ionic-creator.js?8:2:13192)
    at J (http://creator.ionic.io/dist/ionic-creator.js?8:3:29578)
    at Q (http://creator.ionic.io/dist/ionic-creator.js?8:3:30463)
    at HTMLDocument.gt (http://creator.ionic.io/dist/ionic-creator.js?8:4:2628)
TypeError: Cannot read property 'match' of null
    at Object.markId (http://creator.ionic.io/dist/ionic-creator.js?8:2:11457)
    at http://creator.ionic.io/dist/ionic-creator.js?8:3:23817
    at Scope.$emit (http://creator.ionic.io/lib/offline/angular.js:12732:33)
    at Object.obj.appendChild (http://creator.ionic.io/dist/ionic-creator.js?8:1:15889)
    at Object.e.add.obj.addDefaultChildren (http://creator.ionic.io/dist/ionic-creator.js?8:1:9061)
    at Object.createComponent (http://creator.ionic.io/dist/ionic-creator.js?8:2:13192)
    at J (http://creator.ionic.io/dist/ionic-creator.js?8:3:29578)
    at Q (http://creator.ionic.io/dist/ionic-creator.js?8:3:30463)
    at HTMLDocument.gt (http://creator.ionic.io/dist/ionic-creator.js?8:4:2628)
APP OUTLINE
1  page3
2   button-bar1
3    button1
3    button2
3    button3
2   button4
Uncaught TypeError: Cannot read property 'className' of undefined ionic-creator.js:2
GET http://creator.ionic.io/lib/offline/jquery.min.map 404 (Not Found) /lib/offline/jquery.min.map:1
GET http://creator.ionic.io/lib/collide/performance-now.map 404 (Not Found) /lib/collide/performance-now.map:1
GET http://creator.ionic.io/lib/performance-now.map 404 (Not Found) /lib/performance-now.map:1
```

**Comment by Ionitron** [comment]
Greetings @3x14159265!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
